function createfigure5(X1, YMatrix1, X2, YMatrix2, X3, YMatrix3, X4, YMatrix4)
%CREATEFIGURE(X1, YMatrix1, X2, YMatrix2, X3, YMatrix3, X4, YMatrix4)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  X2:  vector of x data
%  YMATRIX2:  matrix of y data
%  X3:  vector of x data
%  YMATRIX3:  matrix of y data
%  X4:  vector of x data
%  YMATRIX4:  matrix of y data

%  Auto-generated by MATLAB on 30-Mar-2022 17:24:40

% Create figure
figure1 = figure('InvertHardcopy','off','Color',[1 1 1]);

% Create axes
axes1 = axes('Position',...
    [0.588156123822342 0.75659229208925 0.357005565987098 0.203737905921021]);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Tag','shadedErrorBar_mainLine');
set(plot1(1),'DisplayName','Households','Marker','square','Color',[0 0 1]);
set(plot1(2),'DisplayName','Social environment','Marker','v',...
    'Color',[1 0 0]);
set(plot1(3),'DisplayName','Workplace','Marker','diamond','Color',[0 1 0]);

% Create ylabel
ylabel({'Infection Occurence','Ratio'});

% Create xlabel
xlabel('R_0');

% Create title
title('No Stay at Home Restriction');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 3]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 1]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-1 1]);
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',8,'GridAlpha',0.3);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.415467337810906 -0.00887069326174763 0.805281766095018 0.0441176460361948],...
    'Orientation','horizontal',...
    'FontWeight','bold',...
    'FontSize',8,...
    'EdgeColor',[1 1 1]);

% Create axes
axes2 = axes('Position',...
    [0.588156123822342 0.433980680015263 0.358565187653068 0.21869714222573]);
hold(axes2,'on');

% Create multiple lines using matrix input to plot
plot2 = plot(X2,YMatrix2,'Tag','shadedErrorBar_mainLine');
set(plot2(1),'Marker','square','Color',[0 0 1]);
set(plot2(2),'Marker','v','Color',[1 0 0]);
set(plot2(3),'Marker','diamond','Color',[0 1 0]);

% Create ylabel
ylabel({'Infection Occurence','Ratio'});

% Create xlabel
xlabel('R_0');

% Create title
title('Stay at Home Restriction on Sunday');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[0 3]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[0 1]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes2,[-1 1]);
grid(axes2,'on');
% Set the remaining axes properties
set(axes2,'FontSize',8,'GridAlpha',0.3);
% Create axes
axes3 = axes('Position',...
    [0.588156123822342 0.102970297029703 0.358565187653068 0.224907886863536]);
hold(axes3,'on');

% Create multiple lines using matrix input to plot
plot3 = plot(X3,YMatrix3,'Tag','shadedErrorBar_mainLine');
set(plot3(1),'Marker','square','Color',[0 0 1]);
set(plot3(2),'Marker','v','Color',[1 0 0]);
set(plot3(3),'Marker','diamond','Color',[0 1 0]);

% Create ylabel
ylabel({'Infection Occurence','Ratio'});

% Create xlabel
xlabel('R_0');

% Create title
title('Stay at Home Restriction  on  Saturday, Sunday');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes3,[0 3]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes3,[0 1]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes3,[-1 1]);
grid(axes3,'on');
% Set the remaining axes properties
set(axes3,'FontSize',8,'GridAlpha',0.3);
% Create axes
axes4 = axes('Position',...
    [0.0696648044692736 0.103741496598639 0.383966480446927 0.862074829931972]);
hold(axes4,'on');

% Create multiple lines using matrix input to plot
plot4 = plot(X4,YMatrix4,'Tag','shadedErrorBar_mainLine','Color',[0 0 0]);
set(plot4(1),'DisplayName','No Stay at Home Restriction','Marker','square');
set(plot4(2),'DisplayName','Stay at Home Restriction on Sunday',...
    'Marker','v');
set(plot4(3),'DisplayName','Stay at Home Restriction  on  Saturday, Sunday',...
    'Marker','diamond');

% Create ylabel
ylabel('R_0');

% Create xlabel
xlabel('Reduction in \beta_o (%)');

grid(axes4,'on');
% Set the remaining axes properties
set(axes4,'FontSize',9,'GridAlpha',0.3);
% Create legend
legend2 = legend(axes4,'show');
set(legend2,...
    'Position',[0.0494037325108846 0.83843537414966 0.463576147641173 0.117913832199546]);

% Create textbox
annotation(figure1,'textbox',...
    [0.480391161334514 0.33779005639515 0.0292197802197804 0.0342741935483869],...
    'String','d)',...
    'FontWeight','bold',...
    'FitBoxToText','off',...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.476089720733706 0.972533883643439 0.0292197802197804 0.0342741935483867],...
    'String','b)',...
    'FontWeight','bold',...
    'FitBoxToText','off',...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.475620240200106 0.65912133526226 0.0292197802197801 0.034274193548387],...
    'String','c)',...
    'FontWeight','bold',...
    'FitBoxToText','off',...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.000474672794660166 0.971432818597697 0.0292197802197803 0.0342741935483865],...
    'String',{'a)'},...
    'FontWeight','bold',...
    'FitBoxToText','off',...
    'EdgeColor','none');

