function createfigure2(X1, YMatrix1, X2, Y1, X3, YMatrix2, X4, YMatrix3, X5, Y2, X6, Y3)
%CREATEFIGURE(X1, YMatrix1, X2, Y1, X3, YMatrix2, X4, YMatrix3, X5, Y2, X6, Y3)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  X2:  vector of x data
%  Y1:  vector of y data
%  X3:  vector of x data
%  YMATRIX2:  matrix of y data
%  X4:  vector of x data
%  YMATRIX3:  matrix of y data
%  X5:  vector of x data
%  Y2:  vector of y data
%  X6:  vector of x data
%  Y3:  vector of y data

%  Auto-generated by MATLAB on 30-Mar-2022 17:19:55

% Create figure
figure1 = figure('InvertHardcopy','off','Color',[1 1 1]);

% Create axes
axes1 = axes('Position',...
    [0.0619039487881884 0.110220440881764 0.465391336571613 0.851703406813627]);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Tag','shadedErrorBar_mainLine','Color',[0 0 0]);
set(plot1(1),'DisplayName','\beta_h fix, \beta_o varies','Marker','square');
set(plot1(2),'DisplayName','\beta_h,  \beta_o varies','Marker','v');
set(plot1(3),'DisplayName','\beta_h,  \beta_o varies  (Random Network)',...
    'Marker','pentagram');

% Create plot
plot(X2,Y1,...
    'DisplayName','\beta_h,  \beta_o varies  (Random Network, Normalized with Respect to Maximum R_0)',...
    'Tag','shadedErrorBar_mainLine',...
    'Marker','hexagram',...
    'Color',[0 0 0]);

% Create ylabel
ylabel('R_0');

% Create xlabel
xlabel('Reduction in \beta_o (%)');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 100]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 7]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-1 1]);
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',8);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.0975720613699427 0.785751688205754 0.426953556381023 0.16933867269623]);

% Create axes
axes2 = axes('Position',...
    [0.650124069478908 0.608108385816489 0.325062034739454 0.350993377483444]);
hold(axes2,'on');

% Create multiple lines using matrix input to plot
plot2 = plot(X3,YMatrix2,'Tag','shadedErrorBar_mainLine');
set(plot2(1),'DisplayName','Households','Marker','square','Color',[0 0 1]);
set(plot2(2),'DisplayName','Social environment','Marker','v',...
    'Color',[1 0 0]);
set(plot2(3),'DisplayName','Workplace','Marker','diamond','Color',[0 1 0]);

% Create ylabel
ylabel({'Infection Occurence','Ratio'});

% Create xlabel
xlabel('R_0');

% Create title
title('\beta_h fix,  \beta_o varies  ');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[0.145374449339207 3.14537444933921]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[0.00875286206996505 1.00875286206996]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes2,[-1 1]);
grid(axes2,'on');
% Set the remaining axes properties
set(axes2,'FontSize',8);
% Create legend
legend2 = legend(axes2,'show');
set(legend2,...
    'Position',[0.462218660892345 0.000843945954078059 0.82602106404208 0.0360721434524399],...
    'Orientation','horizontal',...
    'FontWeight','bold',...
    'FontSize',8,...
    'EdgeColor',[1 1 1]);

% Create axes
axes3 = axes('Position',...
    [0.650124069478908 0.113167145378351 0.315136476426799 0.341986754966887]);
hold(axes3,'on');

% Create multiple lines using matrix input to plot
plot3 = plot(X4,YMatrix3,'Tag','shadedErrorBar_mainLine');
set(plot3(1),'DisplayName','Households','Marker','square','Color',[0 0 1]);
set(plot3(2),'Marker','v','Color',[1 0 0]);
set(plot3(3),'Marker','diamond','Color',[0 1 0]);

% Create ylabel
ylabel({'Infection Occurence','Ratio'});

% Create xlabel
xlabel('R_0');

% Create title
title('\beta_h,  \beta_o varies  ');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes3,[0 3]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes3,[0 1]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes3,[-1 1]);
grid(axes3,'on');
% Set the remaining axes properties
set(axes3,'FontSize',8);
% Create axes
axes4 = axes('Position',...
    [0.10709489956646 0.51826787297293 0.163376564453391 0.219681535778347]);
hold(axes4,'on');

% Create plot
plot(X5,Y2,'Tag','shadedErrorBar_mainLine','Marker','square',...
    'Color',[0 0 0]);

% Create plot
plot(X6,Y3,'Tag','shadedErrorBar_mainLine','Marker','v','Color',[0 0 0]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes4,[80 100]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes4,[0 1.51769642262879]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes4,[-1 1]);
% Set the remaining axes properties
set(axes4,'FontSize',8.5);
% Create arrow
annotation(figure1,'arrow',[0.433575620850959 0.290322580645161],...
    [0.303754478313256 0.49498997995992],'HeadWidth',8,'HeadLength',6);

% Create textbox
annotation(figure1,'textbox',...
    [0.0109795482230145 0.961402105711396 0.0287452945032306 0.0367931728300834],...
    'String',{'a)'},...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FitBoxToText','off',...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.55722741220662 0.957709006422631 0.0287452945032307 0.0367931728300843],...
    'String','b)',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FitBoxToText','off',...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.56312941708065 0.456063055862921 0.0287452945032307 0.0367931728300846],...
    'String','c)',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FitBoxToText','off',...
    'EdgeColor','none');

% Create rectangle
annotation(figure1,'rectangle',...
    [0.424966769612954 0.0698254617342794 0.119106699751861 0.225782646373829],...
    'LineStyle','--');

% Create line
annotation(figure1,'line',[0.94563986409966 0.950169875424689],...
    [0.953081632653061 0.115646258503401],'LineStyle','--');

