function createfigure(X1, Y1, Z1, X2, Y2, Z2, S1, C1, X3, Y3, Z3, C2, X4, Y4, Z4, X5, Y5, Z5)
%CREATEFIGURE(X1, Y1, Z1, X2, Y2, Z2, S1, C1, X3, Y3, Z3, C2, X4, Y4, Z4, X5, Y5, Z5)
%  X1:  scatter3 x
%  Y1:  scatter3 y
%  Z1:  scatter3 z
%  X2:  scatter3 x
%  Y2:  scatter3 y
%  Z2:  scatter3 z
%  S1:  scatter3 s
%  C1:  scatter3 c
%  X3:  scatter3 x
%  Y3:  scatter3 y
%  Z3:  scatter3 z
%  C2:  scatter3 c
%  X4:  scatter3 x
%  Y4:  scatter3 y
%  Z4:  scatter3 z
%  X5:  scatter3 x
%  Y5:  scatter3 y
%  Z5:  scatter3 z

%  Auto-generated by MATLAB on 31-Mar-2022 09:29:09

% Create figure
figure1 = figure;

% Create axes
axes1 = axes;
hold(axes1,'on');

% Create scatter3
scatter3(X1,Y1,Z1,'DisplayName','Total Error >0.14',...
    'MarkerFaceColor',[0.831372559070587 0.815686285495758 0.7843137383461],...
    'MarkerEdgeColor','none');

% Create scatter3
scatter3(X2,Y2,Z2,S1,C1,'DisplayName','Global Minimal (Total Error = 0.07)',...
    'MarkerFaceColor','flat',...
    'MarkerEdgeColor','none');

% Create scatter3
scatter3(X3,Y3,Z3,S1,C2,'DisplayName','Local Minimal (Total Error = 0.095)',...
    'MarkerFaceColor',[0 0.447058826684952 0.74117648601532],...
    'MarkerEdgeColor','none');

% Create scatter3
scatter3(X4,Y4,Z4,S1,C2,'DisplayName','Local Minimal (Total Error = 0.096)',...
    'MarkerFaceColor',[0 0.447058826684952 0.74117648601532],...
    'MarkerEdgeColor','none');

% Create scatter3
scatter3(X5,Y5,Z5,S1,C2,'DisplayName','Local Minimal (Total Error = 0.105)',...
    'MarkerFaceColor',[0 0.447058826684952 0.74117648601532],...
    'MarkerEdgeColor','none');

% Create zlabel
zlabel('Total Error');

% Create ylabel
ylabel('\beta');

% Create xlabel
xlabel('\alpha');

% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[0 5]);
view(axes1,[-44.0111518166585 11.1961030282781]);
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontAngle','italic','FontWeight','bold');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.135370048523434 0.646714181526347 0.372516547705954 0.186274504690778],...
    'FontSize',8);

% Create textarrow
annotation(figure1,'textarrow',[0.652005174644243 0.827943078913325],...
    [0.660080074487896 0.238361266294227],...
    'String',{'\alpha = 0.9841','\beta = 0.1672','R_0 = 2.93','SAR = 0.46'},...
    'HorizontalAlignment','left',...
    'FontWeight','bold');

