function createfigure6d(ymatrix1)
%CREATEFIGURE(ymatrix1)
%  YMATRIX1:  bar matrix data

%  Auto-generated by MATLAB on 30-Mar-2022 16:11:59

% Create figure
figure('OuterPosition',[672 226 576 513]);

% Create axes
axes1 = axes;
hold(axes1,'on');

% Create multiple lines using matrix input to bar
bar1 = bar(ymatrix1,'LineWidth',2,'FaceColor','none');
set(bar1(3),'DisplayName','Home','BarWidth',1);
set(bar1(2),'DisplayName','Work','EdgeColor',[0 1 0]);
set(bar1(1),'DisplayName','Social Environment','EdgeColor',[1 0 0],...
    'BarWidth',0.6);

% Create ylabel
ylabel('Number of encounters');

% Create xlabel
xlabel('Time (houre)');

% Create title
title('3 Hour Decrease in Work  ');

box(axes1,'on');
grid(axes1,'on');
